// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPriceSubmitter$Type } from "./IPriceSubmitter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPriceSubmitter"]: IPriceSubmitter$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPriceSubmitter.sol:IPriceSubmitter"]: IPriceSubmitter$Type;
  }

  interface ContractTypesMap {
    ["IPriceSubmitter"]: GetContractReturnType<IPriceSubmitter$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPriceSubmitter.sol:IPriceSubmitter"]: GetContractReturnType<IPriceSubmitter$Type["abi"]>;
  }
}
