// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IConfirmedBlockHeightExistsVerification$Type } from "./IConfirmedBlockHeightExistsVerification";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IConfirmedBlockHeightExistsVerification"]: IConfirmedBlockHeightExistsVerification$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IConfirmedBlockHeightExistsVerification.sol:IConfirmedBlockHeightExistsVerification"]: IConfirmedBlockHeightExistsVerification$Type;
  }

  interface ContractTypesMap {
    ["IConfirmedBlockHeightExistsVerification"]: GetContractReturnType<IConfirmedBlockHeightExistsVerification$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IConfirmedBlockHeightExistsVerification.sol:IConfirmedBlockHeightExistsVerification"]: GetContractReturnType<IConfirmedBlockHeightExistsVerification$Type["abi"]>;
  }
}
