// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ContractRegistry$Type } from "./ContractRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ContractRegistry"]: ContractRegistry$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/ContractRegistry.sol:ContractRegistry"]: ContractRegistry$Type;
  }

  interface ContractTypesMap {
    ["ContractRegistry"]: GetContractReturnType<ContractRegistry$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/ContractRegistry.sol:ContractRegistry"]: GetContractReturnType<ContractRegistry$Type["abi"]>;
  }
}
