// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ContractRegistry$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ContractRegistry",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/ContractRegistry.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220564d3090aba91fd84029b0d8ff40acf6f196b39ccca43360e3811ce4159e5eff64736f6c634300081c0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220564d3090aba91fd84029b0d8ff40acf6f196b39ccca43360e3811ce4159e5eff64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ContractRegistry",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ContractRegistry$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/ContractRegistry.sol:ContractRegistry",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ContractRegistry$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ContractRegistry",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ContractRegistry$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/ContractRegistry.sol:ContractRegistry",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ContractRegistry$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ContractRegistry",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ContractRegistry$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/ContractRegistry.sol:ContractRegistry",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ContractRegistry$Type["abi"]>>;
}
