// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoGenesis$Type } from "./IFtsoGenesis";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoGenesis"]: IFtsoGenesis$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoGenesis.sol:IFtsoGenesis"]: IFtsoGenesis$Type;
  }

  interface ContractTypesMap {
    ["IFtsoGenesis"]: GetContractReturnType<IFtsoGenesis$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoGenesis.sol:IFtsoGenesis"]: GetContractReturnType<IFtsoGenesis$Type["abi"]>;
  }
}
