// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFtsoGenesis$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFtsoGenesis",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoGenesis.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_voter",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "_epochId",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_price",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "_wNatVP",
          "type": "uint256"
        }
      ],
      "name": "revealPriceSubmitter",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_voter",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "_epochId",
          "type": "uint256"
        }
      ],
      "name": "wNatVotePowerCached",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFtsoGenesis",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoGenesis$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoGenesis.sol:IFtsoGenesis",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoGenesis$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFtsoGenesis",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoGenesis$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoGenesis.sol:IFtsoGenesis",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoGenesis$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFtsoGenesis",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoGenesis$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoGenesis.sol:IFtsoGenesis",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoGenesis$Type["abi"]>>;
}
