// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IVoterRegistry$Type } from "./IVoterRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVoterRegistry"]: IVoterRegistry$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IVoterRegistry.sol:IVoterRegistry"]: IVoterRegistry$Type;
  }

  interface ContractTypesMap {
    ["IVoterRegistry"]: GetContractReturnType<IVoterRegistry$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IVoterRegistry.sol:IVoterRegistry"]: GetContractReturnType<IVoterRegistry$Type["abi"]>;
  }
}
