// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IVoterRegistry$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IVoterRegistry",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IVoterRegistry.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes20",
          "name": "beneficiary",
          "type": "bytes20"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "untilRewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "BeneficiaryChilled",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "voter",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "uint24",
          "name": "rewardEpochId",
          "type": "uint24"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "signingPolicyAddress",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "submitAddress",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "submitSignaturesAddress",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "publicKeyPart1",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "publicKeyPart2",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "registrationWeight",
          "type": "uint256"
        }
      ],
      "name": "VoterRegistered",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "voter",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "rewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "VoterRemoved",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "bytes20",
          "name": "_beneficiary",
          "type": "bytes20"
        }
      ],
      "name": "chilledUntilRewardEpochId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "_rewardEpochId",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_rewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "getNumberOfRegisteredVoters",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_rewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "getRegisteredVoters",
      "outputs": [
        {
          "internalType": "address[]",
          "name": "",
          "type": "address[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_voter",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "_rewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "isVoterRegistered",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "maxVoters",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_rewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "newSigningPolicyInitializationStartBlockNumber",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "publicKeyRequired",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_voter",
          "type": "address"
        },
        {
          "components": [
            {
              "internalType": "uint8",
              "name": "v",
              "type": "uint8"
            },
            {
              "internalType": "bytes32",
              "name": "r",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "s",
              "type": "bytes32"
            }
          ],
          "internalType": "struct IVoterRegistry.Signature",
          "name": "_signature",
          "type": "tuple"
        }
      ],
      "name": "registerVoter",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IVoterRegistry",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IVoterRegistry$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IVoterRegistry.sol:IVoterRegistry",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IVoterRegistry$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IVoterRegistry",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IVoterRegistry$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IVoterRegistry.sol:IVoterRegistry",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IVoterRegistry$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IVoterRegistry",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IVoterRegistry$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IVoterRegistry.sol:IVoterRegistry",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IVoterRegistry$Type["abi"]>>;
}
