// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IIGovernanceVotePower$Type } from "./IIGovernanceVotePower";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IIGovernanceVotePower"]: IIGovernanceVotePower$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/token/interface/IIGovernanceVotePower.sol:IIGovernanceVotePower"]: IIGovernanceVotePower$Type;
  }

  interface ContractTypesMap {
    ["IIGovernanceVotePower"]: GetContractReturnType<IIGovernanceVotePower$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/token/interface/IIGovernanceVotePower.sol:IIGovernanceVotePower"]: GetContractReturnType<IIGovernanceVotePower$Type["abi"]>;
  }
}
