// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IJsonApiVerification$Type } from "./IJsonApiVerification";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IJsonApiVerification"]: IJsonApiVerification$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IJsonApiVerification.sol:IJsonApiVerification"]: IJsonApiVerification$Type;
  }

  interface ContractTypesMap {
    ["IJsonApiVerification"]: GetContractReturnType<IJsonApiVerification$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IJsonApiVerification.sol:IJsonApiVerification"]: GetContractReturnType<IJsonApiVerification$Type["abi"]>;
  }
}
