// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFastUpdater$Type } from "./IFastUpdater";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFastUpdater"]: IFastUpdater$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFastUpdater.sol:IFastUpdater"]: IFastUpdater$Type;
  }

  interface ContractTypesMap {
    ["IFastUpdater"]: GetContractReturnType<IFastUpdater$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFastUpdater.sol:IFastUpdater"]: GetContractReturnType<IFastUpdater$Type["abi"]>;
  }
}
