// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoRewardManager$Type } from "./IFtsoRewardManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoRewardManager"]: IFtsoRewardManager$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoRewardManager.sol:IFtsoRewardManager"]: IFtsoRewardManager$Type;
  }

  interface ContractTypesMap {
    ["IFtsoRewardManager"]: GetContractReturnType<IFtsoRewardManager$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoRewardManager.sol:IFtsoRewardManager"]: GetContractReturnType<IFtsoRewardManager$Type["abi"]>;
  }
}
