// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IWeb2JsonVerification$Type } from "./IWeb2JsonVerification";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IWeb2JsonVerification"]: IWeb2JsonVerification$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IWeb2JsonVerification.sol:IWeb2JsonVerification"]: IWeb2JsonVerification$Type;
  }

  interface ContractTypesMap {
    ["IWeb2JsonVerification"]: GetContractReturnType<IWeb2JsonVerification$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IWeb2JsonVerification.sol:IWeb2JsonVerification"]: GetContractReturnType<IWeb2JsonVerification$Type["abi"]>;
  }
}
