// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IAddressValidity$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IAddressValidity",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IAddressValidity.sol",
  "abi": [],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IAddressValidity",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAddressValidity$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressValidity.sol:IAddressValidity",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAddressValidity$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IAddressValidity",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAddressValidity$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressValidity.sol:IAddressValidity",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAddressValidity$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IAddressValidity",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAddressValidity$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressValidity.sol:IAddressValidity",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAddressValidity$Type["abi"]>>;
}
