// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFdcHub$Type } from "./IFdcHub";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFdcHub"]: IFdcHub$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFdcHub.sol:IFdcHub"]: IFdcHub$Type;
  }

  interface ContractTypesMap {
    ["IFdcHub"]: GetContractReturnType<IFdcHub$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFdcHub.sol:IFdcHub"]: GetContractReturnType<IFdcHub$Type["abi"]>;
  }
}
