// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFdcHub$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFdcHub",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFdcHub.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "bytes",
          "name": "data",
          "type": "bytes"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "fee",
          "type": "uint256"
        }
      ],
      "name": "AttestationRequest",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint24",
          "name": "rewardEpochId",
          "type": "uint24"
        },
        {
          "components": [
            {
              "internalType": "bytes32",
              "name": "attestationType",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "source",
              "type": "bytes32"
            },
            {
              "internalType": "uint24",
              "name": "inflationShare",
              "type": "uint24"
            },
            {
              "internalType": "uint8",
              "name": "minRequestsThreshold",
              "type": "uint8"
            },
            {
              "internalType": "uint224",
              "name": "mode",
              "type": "uint224"
            }
          ],
          "indexed": false,
          "internalType": "struct IFdcInflationConfigurations.FdcConfiguration[]",
          "name": "fdcConfigurations",
          "type": "tuple[]"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "InflationRewardsOffered",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint8",
          "name": "requestsOffsetSeconds",
          "type": "uint8"
        }
      ],
      "name": "RequestsOffsetSet",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "fdcInflationConfigurations",
      "outputs": [
        {
          "internalType": "contract IFdcInflationConfigurations",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "fdcRequestFeeConfigurations",
      "outputs": [
        {
          "internalType": "contract IFdcRequestFeeConfigurations",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "_data",
          "type": "bytes"
        }
      ],
      "name": "requestAttestation",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "requestsOffsetSeconds",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "",
          "type": "uint8"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFdcHub",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFdcHub$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcHub.sol:IFdcHub",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFdcHub$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFdcHub",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFdcHub$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcHub.sol:IFdcHub",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFdcHub$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFdcHub",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFdcHub$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcHub.sol:IFdcHub",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFdcHub$Type["abi"]>>;
}
