// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IIVPToken$Type } from "./IIVPToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IIVPToken"]: IIVPToken$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/token/interface/IIVPToken.sol:IIVPToken"]: IIVPToken$Type;
  }

  interface ContractTypesMap {
    ["IIVPToken"]: GetContractReturnType<IIVPToken$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/token/interface/IIVPToken.sol:IIVPToken"]: GetContractReturnType<IIVPToken$Type["abi"]>;
  }
}
