// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFdcVerification$Type } from "./IFdcVerification";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFdcVerification"]: IFdcVerification$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFdcVerification.sol:IFdcVerification"]: IFdcVerification$Type;
  }

  interface ContractTypesMap {
    ["IFdcVerification"]: GetContractReturnType<IFdcVerification$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFdcVerification.sol:IFdcVerification"]: GetContractReturnType<IFdcVerification$Type["abi"]>;
  }
}
