// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IJsonApi$Type } from "./IJsonApi";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IJsonApi"]: IJsonApi$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IJsonApi.sol:IJsonApi"]: IJsonApi$Type;
  }

  interface ContractTypesMap {
    ["IJsonApi"]: GetContractReturnType<IJsonApi$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IJsonApi.sol:IJsonApi"]: GetContractReturnType<IJsonApi$Type["abi"]>;
  }
}
