// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoInflationConfigurations$Type } from "./IFtsoInflationConfigurations";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoInflationConfigurations"]: IFtsoInflationConfigurations$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoInflationConfigurations.sol:IFtsoInflationConfigurations"]: IFtsoInflationConfigurations$Type;
  }

  interface ContractTypesMap {
    ["IFtsoInflationConfigurations"]: GetContractReturnType<IFtsoInflationConfigurations$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoInflationConfigurations.sol:IFtsoInflationConfigurations"]: GetContractReturnType<IFtsoInflationConfigurations$Type["abi"]>;
  }
}
