// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFtsoInflationConfigurations$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFtsoInflationConfigurations",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFtsoInflationConfigurations.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_index",
          "type": "uint256"
        }
      ],
      "name": "getFtsoConfiguration",
      "outputs": [
        {
          "components": [
            {
              "internalType": "bytes",
              "name": "feedIds",
              "type": "bytes"
            },
            {
              "internalType": "uint24",
              "name": "inflationShare",
              "type": "uint24"
            },
            {
              "internalType": "uint16",
              "name": "minRewardedTurnoutBIPS",
              "type": "uint16"
            },
            {
              "internalType": "uint24",
              "name": "primaryBandRewardSharePPM",
              "type": "uint24"
            },
            {
              "internalType": "bytes",
              "name": "secondaryBandWidthPPMs",
              "type": "bytes"
            },
            {
              "internalType": "uint16",
              "name": "mode",
              "type": "uint16"
            }
          ],
          "internalType": "struct IFtsoInflationConfigurations.FtsoConfiguration",
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getFtsoConfigurations",
      "outputs": [
        {
          "components": [
            {
              "internalType": "bytes",
              "name": "feedIds",
              "type": "bytes"
            },
            {
              "internalType": "uint24",
              "name": "inflationShare",
              "type": "uint24"
            },
            {
              "internalType": "uint16",
              "name": "minRewardedTurnoutBIPS",
              "type": "uint16"
            },
            {
              "internalType": "uint24",
              "name": "primaryBandRewardSharePPM",
              "type": "uint24"
            },
            {
              "internalType": "bytes",
              "name": "secondaryBandWidthPPMs",
              "type": "bytes"
            },
            {
              "internalType": "uint16",
              "name": "mode",
              "type": "uint16"
            }
          ],
          "internalType": "struct IFtsoInflationConfigurations.FtsoConfiguration[]",
          "name": "",
          "type": "tuple[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFtsoInflationConfigurations",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoInflationConfigurations$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFtsoInflationConfigurations.sol:IFtsoInflationConfigurations",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoInflationConfigurations$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFtsoInflationConfigurations",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoInflationConfigurations$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFtsoInflationConfigurations.sol:IFtsoInflationConfigurations",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoInflationConfigurations$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFtsoInflationConfigurations",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoInflationConfigurations$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFtsoInflationConfigurations.sol:IFtsoInflationConfigurations",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoInflationConfigurations$Type["abi"]>>;
}
