// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPChainStakeMirrorVerifier$Type } from "./IPChainStakeMirrorVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPChainStakeMirrorVerifier"]: IPChainStakeMirrorVerifier$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPChainStakeMirrorVerifier.sol:IPChainStakeMirrorVerifier"]: IPChainStakeMirrorVerifier$Type;
  }

  interface ContractTypesMap {
    ["IPChainStakeMirrorVerifier"]: GetContractReturnType<IPChainStakeMirrorVerifier$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPChainStakeMirrorVerifier.sol:IPChainStakeMirrorVerifier"]: GetContractReturnType<IPChainStakeMirrorVerifier$Type["abi"]>;
  }
}
