// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFeeCalculator$Type } from "./IFeeCalculator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFeeCalculator"]: IFeeCalculator$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFeeCalculator.sol:IFeeCalculator"]: IFeeCalculator$Type;
  }

  interface ContractTypesMap {
    ["IFeeCalculator"]: GetContractReturnType<IFeeCalculator$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFeeCalculator.sol:IFeeCalculator"]: GetContractReturnType<IFeeCalculator$Type["abi"]>;
  }
}
