// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFeeCalculator$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFeeCalculator",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFeeCalculator.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes21[]",
          "name": "_feedIds",
          "type": "bytes21[]"
        }
      ],
      "name": "calculateFeeByIds",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "_fee",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256[]",
          "name": "_indices",
          "type": "uint256[]"
        }
      ],
      "name": "calculateFeeByIndices",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "_fee",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFeeCalculator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFeeCalculator$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFeeCalculator.sol:IFeeCalculator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFeeCalculator$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFeeCalculator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFeeCalculator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFeeCalculator.sol:IFeeCalculator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFeeCalculator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFeeCalculator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFeeCalculator$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFeeCalculator.sol:IFeeCalculator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFeeCalculator$Type["abi"]>>;
}
