// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IEVMTransactionVerification$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IEVMTransactionVerification",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IEVMTransactionVerification.sol",
  "abi": [
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "bytes32[]",
              "name": "merkleProof",
              "type": "bytes32[]"
            },
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "attestationType",
                  "type": "bytes32"
                },
                {
                  "internalType": "bytes32",
                  "name": "sourceId",
                  "type": "bytes32"
                },
                {
                  "internalType": "uint64",
                  "name": "votingRound",
                  "type": "uint64"
                },
                {
                  "internalType": "uint64",
                  "name": "lowestUsedTimestamp",
                  "type": "uint64"
                },
                {
                  "components": [
                    {
                      "internalType": "bytes32",
                      "name": "transactionHash",
                      "type": "bytes32"
                    },
                    {
                      "internalType": "uint16",
                      "name": "requiredConfirmations",
                      "type": "uint16"
                    },
                    {
                      "internalType": "bool",
                      "name": "provideInput",
                      "type": "bool"
                    },
                    {
                      "internalType": "bool",
                      "name": "listEvents",
                      "type": "bool"
                    },
                    {
                      "internalType": "uint32[]",
                      "name": "logIndices",
                      "type": "uint32[]"
                    }
                  ],
                  "internalType": "struct IEVMTransaction.RequestBody",
                  "name": "requestBody",
                  "type": "tuple"
                },
                {
                  "components": [
                    {
                      "internalType": "uint64",
                      "name": "blockNumber",
                      "type": "uint64"
                    },
                    {
                      "internalType": "uint64",
                      "name": "timestamp",
                      "type": "uint64"
                    },
                    {
                      "internalType": "address",
                      "name": "sourceAddress",
                      "type": "address"
                    },
                    {
                      "internalType": "bool",
                      "name": "isDeployment",
                      "type": "bool"
                    },
                    {
                      "internalType": "address",
                      "name": "receivingAddress",
                      "type": "address"
                    },
                    {
                      "internalType": "uint256",
                      "name": "value",
                      "type": "uint256"
                    },
                    {
                      "internalType": "bytes",
                      "name": "input",
                      "type": "bytes"
                    },
                    {
                      "internalType": "uint8",
                      "name": "status",
                      "type": "uint8"
                    },
                    {
                      "components": [
                        {
                          "internalType": "uint32",
                          "name": "logIndex",
                          "type": "uint32"
                        },
                        {
                          "internalType": "address",
                          "name": "emitterAddress",
                          "type": "address"
                        },
                        {
                          "internalType": "bytes32[]",
                          "name": "topics",
                          "type": "bytes32[]"
                        },
                        {
                          "internalType": "bytes",
                          "name": "data",
                          "type": "bytes"
                        },
                        {
                          "internalType": "bool",
                          "name": "removed",
                          "type": "bool"
                        }
                      ],
                      "internalType": "struct IEVMTransaction.Event[]",
                      "name": "events",
                      "type": "tuple[]"
                    }
                  ],
                  "internalType": "struct IEVMTransaction.ResponseBody",
                  "name": "responseBody",
                  "type": "tuple"
                }
              ],
              "internalType": "struct IEVMTransaction.Response",
              "name": "data",
              "type": "tuple"
            }
          ],
          "internalType": "struct IEVMTransaction.Proof",
          "name": "_proof",
          "type": "tuple"
        }
      ],
      "name": "verifyEVMTransaction",
      "outputs": [
        {
          "internalType": "bool",
          "name": "_proved",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IEVMTransactionVerification",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IEVMTransactionVerification$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IEVMTransactionVerification.sol:IEVMTransactionVerification",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IEVMTransactionVerification$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IEVMTransactionVerification",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IEVMTransactionVerification$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IEVMTransactionVerification.sol:IEVMTransactionVerification",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IEVMTransactionVerification$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IEVMTransactionVerification",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IEVMTransactionVerification$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IEVMTransactionVerification.sol:IEVMTransactionVerification",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IEVMTransactionVerification$Type["abi"]>>;
}
