// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEntityManager$Type } from "./IEntityManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEntityManager"]: IEntityManager$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IEntityManager.sol:IEntityManager"]: IEntityManager$Type;
  }

  interface ContractTypesMap {
    ["IEntityManager"]: GetContractReturnType<IEntityManager$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IEntityManager.sol:IEntityManager"]: GetContractReturnType<IEntityManager$Type["abi"]>;
  }
}
