// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IGenericRewardManager$Type } from "./IGenericRewardManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IGenericRewardManager"]: IGenericRewardManager$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IGenericRewardManager.sol:IGenericRewardManager"]: IGenericRewardManager$Type;
  }

  interface ContractTypesMap {
    ["IGenericRewardManager"]: GetContractReturnType<IGenericRewardManager$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IGenericRewardManager.sol:IGenericRewardManager"]: GetContractReturnType<IGenericRewardManager$Type["abi"]>;
  }
}
