// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ClickToken$Type } from "./ClickToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ClickToken"]: ClickToken$Type;
    ["contracts/ClickToken.sol:ClickToken"]: ClickToken$Type;
  }

  interface ContractTypesMap {
    ["ClickToken"]: GetContractReturnType<ClickToken$Type["abi"]>;
    ["contracts/ClickToken.sol:ClickToken"]: GetContractReturnType<ClickToken$Type["abi"]>;
  }
}
