// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IGovernanceSettings$Type } from "./IGovernanceSettings";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IGovernanceSettings"]: IGovernanceSettings$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IGovernanceSettings.sol:IGovernanceSettings"]: IGovernanceSettings$Type;
  }

  interface ContractTypesMap {
    ["IGovernanceSettings"]: GetContractReturnType<IGovernanceSettings$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IGovernanceSettings.sol:IGovernanceSettings"]: GetContractReturnType<IGovernanceSettings$Type["abi"]>;
  }
}
