// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IGovernanceSettings$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IGovernanceSettings",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IGovernanceSettings.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getExecutors",
      "outputs": [
        {
          "internalType": "address[]",
          "name": "",
          "type": "address[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getGovernanceAddress",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getTimelock",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_address",
          "type": "address"
        }
      ],
      "name": "isExecutor",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IGovernanceSettings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IGovernanceSettings$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IGovernanceSettings.sol:IGovernanceSettings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IGovernanceSettings$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IGovernanceSettings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IGovernanceSettings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IGovernanceSettings.sol:IGovernanceSettings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IGovernanceSettings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IGovernanceSettings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IGovernanceSettings$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IGovernanceSettings.sol:IGovernanceSettings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IGovernanceSettings$Type["abi"]>>;
}
