// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFastUpdateIncentiveManager$Type } from "./IFastUpdateIncentiveManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFastUpdateIncentiveManager"]: IFastUpdateIncentiveManager$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFastUpdateIncentiveManager.sol:IFastUpdateIncentiveManager"]: IFastUpdateIncentiveManager$Type;
  }

  interface ContractTypesMap {
    ["IFastUpdateIncentiveManager"]: GetContractReturnType<IFastUpdateIncentiveManager$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFastUpdateIncentiveManager.sol:IFastUpdateIncentiveManager"]: GetContractReturnType<IFastUpdateIncentiveManager$Type["abi"]>;
  }
}
