// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFastUpdateIncentiveManager$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFastUpdateIncentiveManager",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFastUpdateIncentiveManager.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint24",
          "name": "rewardEpochId",
          "type": "uint24"
        },
        {
          "indexed": false,
          "internalType": "Range",
          "name": "rangeIncrease",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "SampleSize",
          "name": "sampleSizeIncrease",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "Fee",
          "name": "offerAmount",
          "type": "uint256"
        }
      ],
      "name": "IncentiveOffered",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint24",
          "name": "rewardEpochId",
          "type": "uint24"
        },
        {
          "components": [
            {
              "internalType": "bytes21",
              "name": "feedId",
              "type": "bytes21"
            },
            {
              "internalType": "uint32",
              "name": "rewardBandValue",
              "type": "uint32"
            },
            {
              "internalType": "uint24",
              "name": "inflationShare",
              "type": "uint24"
            }
          ],
          "indexed": false,
          "internalType": "struct IFastUpdatesConfiguration.FeedConfiguration[]",
          "name": "feedConfigurations",
          "type": "tuple[]"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "InflationRewardsOffered",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "getBaseScale",
      "outputs": [
        {
          "internalType": "Scale",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getCurrentSampleSizeIncreasePrice",
      "outputs": [
        {
          "internalType": "Fee",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getExpectedSampleSize",
      "outputs": [
        {
          "internalType": "SampleSize",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getIncentiveDuration",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getPrecision",
      "outputs": [
        {
          "internalType": "Precision",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getRange",
      "outputs": [
        {
          "internalType": "Range",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getScale",
      "outputs": [
        {
          "internalType": "Scale",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "Range",
              "name": "rangeIncrease",
              "type": "uint256"
            },
            {
              "internalType": "Range",
              "name": "rangeLimit",
              "type": "uint256"
            }
          ],
          "internalType": "struct IFastUpdateIncentiveManager.IncentiveOffer",
          "name": "_offer",
          "type": "tuple"
        }
      ],
      "name": "offerIncentive",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "rangeIncreaseLimit",
      "outputs": [
        {
          "internalType": "Range",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "rangeIncreasePrice",
      "outputs": [
        {
          "internalType": "Fee",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "sampleIncreaseLimit",
      "outputs": [
        {
          "internalType": "SampleSize",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFastUpdateIncentiveManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFastUpdateIncentiveManager$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFastUpdateIncentiveManager.sol:IFastUpdateIncentiveManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFastUpdateIncentiveManager$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFastUpdateIncentiveManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFastUpdateIncentiveManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFastUpdateIncentiveManager.sol:IFastUpdateIncentiveManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFastUpdateIncentiveManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFastUpdateIncentiveManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFastUpdateIncentiveManager$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFastUpdateIncentiveManager.sol:IFastUpdateIncentiveManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFastUpdateIncentiveManager$Type["abi"]>>;
}
