// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IWNatDelegationFee$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IWNatDelegationFee",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IWNatDelegationFee.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "voter",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint16",
          "name": "value",
          "type": "uint16"
        },
        {
          "indexed": false,
          "internalType": "uint24",
          "name": "validFromEpochId",
          "type": "uint24"
        }
      ],
      "name": "FeePercentageChanged",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "defaultFeePercentageBIPS",
      "outputs": [
        {
          "internalType": "uint16",
          "name": "",
          "type": "uint16"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "feePercentageUpdateOffset",
      "outputs": [
        {
          "internalType": "uint24",
          "name": "",
          "type": "uint24"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_voter",
          "type": "address"
        }
      ],
      "name": "getVoterCurrentFeePercentage",
      "outputs": [
        {
          "internalType": "uint16",
          "name": "",
          "type": "uint16"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_voter",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "_rewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "getVoterFeePercentage",
      "outputs": [
        {
          "internalType": "uint16",
          "name": "",
          "type": "uint16"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_voter",
          "type": "address"
        }
      ],
      "name": "getVoterScheduledFeePercentageChanges",
      "outputs": [
        {
          "internalType": "uint256[]",
          "name": "_feePercentageBIPS",
          "type": "uint256[]"
        },
        {
          "internalType": "uint256[]",
          "name": "_validFromEpochId",
          "type": "uint256[]"
        },
        {
          "internalType": "bool[]",
          "name": "_fixed",
          "type": "bool[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint16",
          "name": "_feePercentageBIPS",
          "type": "uint16"
        }
      ],
      "name": "setVoterFeePercentage",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IWNatDelegationFee",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IWNatDelegationFee$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IWNatDelegationFee.sol:IWNatDelegationFee",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IWNatDelegationFee$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IWNatDelegationFee",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IWNatDelegationFee$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IWNatDelegationFee.sol:IWNatDelegationFee",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IWNatDelegationFee$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IWNatDelegationFee",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IWNatDelegationFee$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IWNatDelegationFee.sol:IWNatDelegationFee",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IWNatDelegationFee$Type["abi"]>>;
}
