// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RandomNumberV2Interface$Type } from "./RandomNumberV2Interface";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RandomNumberV2Interface"]: RandomNumberV2Interface$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/RandomNumberV2Interface.sol:RandomNumberV2Interface"]: RandomNumberV2Interface$Type;
  }

  interface ContractTypesMap {
    ["RandomNumberV2Interface"]: GetContractReturnType<RandomNumberV2Interface$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/RandomNumberV2Interface.sol:RandomNumberV2Interface"]: GetContractReturnType<RandomNumberV2Interface$Type["abi"]>;
  }
}
