// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface RandomNumberV2Interface$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "RandomNumberV2Interface",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/RandomNumberV2Interface.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getRandomNumber",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "_randomNumber",
          "type": "uint256"
        },
        {
          "internalType": "bool",
          "name": "_isSecureRandom",
          "type": "bool"
        },
        {
          "internalType": "uint256",
          "name": "_randomTimestamp",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_votingRoundId",
          "type": "uint256"
        }
      ],
      "name": "getRandomNumberHistorical",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "_randomNumber",
          "type": "uint256"
        },
        {
          "internalType": "bool",
          "name": "_isSecureRandom",
          "type": "bool"
        },
        {
          "internalType": "uint256",
          "name": "_randomTimestamp",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "RandomNumberV2Interface",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RandomNumberV2Interface$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/RandomNumberV2Interface.sol:RandomNumberV2Interface",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RandomNumberV2Interface$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "RandomNumberV2Interface",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RandomNumberV2Interface$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/RandomNumberV2Interface.sol:RandomNumberV2Interface",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RandomNumberV2Interface$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "RandomNumberV2Interface",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RandomNumberV2Interface$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/RandomNumberV2Interface.sol:RandomNumberV2Interface",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RandomNumberV2Interface$Type["abi"]>>;
}
