// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IWeb2Json$Type } from "./IWeb2Json";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IWeb2Json"]: IWeb2Json$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IWeb2Json.sol:IWeb2Json"]: IWeb2Json$Type;
  }

  interface ContractTypesMap {
    ["IWeb2Json"]: GetContractReturnType<IWeb2Json$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IWeb2Json.sol:IWeb2Json"]: GetContractReturnType<IWeb2Json$Type["abi"]>;
  }
}
