// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IRNat$Type } from "./IRNat";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRNat"]: IRNat$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRNat.sol:IRNat"]: IRNat$Type;
  }

  interface ContractTypesMap {
    ["IRNat"]: GetContractReturnType<IRNat$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRNat.sol:IRNat"]: GetContractReturnType<IRNat$Type["abi"]>;
  }
}
