// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IEVMTransaction$Type } from "./IEVMTransaction";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IEVMTransaction"]: IEVMTransaction$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IEVMTransaction.sol:IEVMTransaction"]: IEVMTransaction$Type;
  }

  interface ContractTypesMap {
    ["IEVMTransaction"]: GetContractReturnType<IEVMTransaction$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IEVMTransaction.sol:IEVMTransaction"]: GetContractReturnType<IEVMTransaction$Type["abi"]>;
  }
}
