// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFdcRequestFeeConfigurations$Type } from "./IFdcRequestFeeConfigurations";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFdcRequestFeeConfigurations"]: IFdcRequestFeeConfigurations$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFdcRequestFeeConfigurations.sol:IFdcRequestFeeConfigurations"]: IFdcRequestFeeConfigurations$Type;
  }

  interface ContractTypesMap {
    ["IFdcRequestFeeConfigurations"]: GetContractReturnType<IFdcRequestFeeConfigurations$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFdcRequestFeeConfigurations.sol:IFdcRequestFeeConfigurations"]: GetContractReturnType<IFdcRequestFeeConfigurations$Type["abi"]>;
  }
}
