// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFdcRequestFeeConfigurations$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFdcRequestFeeConfigurations",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFdcRequestFeeConfigurations.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "attestationType",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "source",
          "type": "bytes32"
        }
      ],
      "name": "TypeAndSourceFeeRemoved",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "attestationType",
          "type": "bytes32"
        },
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "source",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "fee",
          "type": "uint256"
        }
      ],
      "name": "TypeAndSourceFeeSet",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "_data",
          "type": "bytes"
        }
      ],
      "name": "getRequestFee",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFdcRequestFeeConfigurations",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFdcRequestFeeConfigurations$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcRequestFeeConfigurations.sol:IFdcRequestFeeConfigurations",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFdcRequestFeeConfigurations$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFdcRequestFeeConfigurations",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFdcRequestFeeConfigurations$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcRequestFeeConfigurations.sol:IFdcRequestFeeConfigurations",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFdcRequestFeeConfigurations$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFdcRequestFeeConfigurations",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFdcRequestFeeConfigurations$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcRequestFeeConfigurations.sol:IFdcRequestFeeConfigurations",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFdcRequestFeeConfigurations$Type["abi"]>>;
}
