// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFastUpdatesConfiguration$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFastUpdatesConfiguration",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFastUpdatesConfiguration.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes21",
          "name": "feedId",
          "type": "bytes21"
        },
        {
          "indexed": false,
          "internalType": "uint32",
          "name": "rewardBandValue",
          "type": "uint32"
        },
        {
          "indexed": false,
          "internalType": "uint24",
          "name": "inflationShare",
          "type": "uint24"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "FeedAdded",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes21",
          "name": "feedId",
          "type": "bytes21"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "FeedRemoved",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes21",
          "name": "feedId",
          "type": "bytes21"
        },
        {
          "indexed": false,
          "internalType": "uint32",
          "name": "rewardBandValue",
          "type": "uint32"
        },
        {
          "indexed": false,
          "internalType": "uint24",
          "name": "inflationShare",
          "type": "uint24"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "index",
          "type": "uint256"
        }
      ],
      "name": "FeedUpdated",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "getFeedConfigurations",
      "outputs": [
        {
          "components": [
            {
              "internalType": "bytes21",
              "name": "feedId",
              "type": "bytes21"
            },
            {
              "internalType": "uint32",
              "name": "rewardBandValue",
              "type": "uint32"
            },
            {
              "internalType": "uint24",
              "name": "inflationShare",
              "type": "uint24"
            }
          ],
          "internalType": "struct IFastUpdatesConfiguration.FeedConfiguration[]",
          "name": "",
          "type": "tuple[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_index",
          "type": "uint256"
        }
      ],
      "name": "getFeedId",
      "outputs": [
        {
          "internalType": "bytes21",
          "name": "_feedId",
          "type": "bytes21"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getFeedIds",
      "outputs": [
        {
          "internalType": "bytes21[]",
          "name": "",
          "type": "bytes21[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes21",
          "name": "_feedId",
          "type": "bytes21"
        }
      ],
      "name": "getFeedIndex",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "_index",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getNumberOfFeeds",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getUnusedIndices",
      "outputs": [
        {
          "internalType": "uint256[]",
          "name": "",
          "type": "uint256[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFastUpdatesConfiguration",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFastUpdatesConfiguration$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFastUpdatesConfiguration.sol:IFastUpdatesConfiguration",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFastUpdatesConfiguration$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFastUpdatesConfiguration",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFastUpdatesConfiguration$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFastUpdatesConfiguration.sol:IFastUpdatesConfiguration",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFastUpdatesConfiguration$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFastUpdatesConfiguration",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFastUpdatesConfiguration$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFastUpdatesConfiguration.sol:IFastUpdatesConfiguration",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFastUpdatesConfiguration$Type["abi"]>>;
}
