// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AchievementTokens$Type } from "./AchievementTokens";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AchievementTokens"]: AchievementTokens$Type;
    ["contracts/AchievementTokens.sol:AchievementTokens"]: AchievementTokens$Type;
  }

  interface ContractTypesMap {
    ["AchievementTokens"]: GetContractReturnType<AchievementTokens$Type["abi"]>;
    ["contracts/AchievementTokens.sol:AchievementTokens"]: GetContractReturnType<AchievementTokens$Type["abi"]>;
  }
}
