// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPChainStakeMirror$Type } from "./IPChainStakeMirror";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPChainStakeMirror"]: IPChainStakeMirror$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPChainStakeMirror.sol:IPChainStakeMirror"]: IPChainStakeMirror$Type;
  }

  interface ContractTypesMap {
    ["IPChainStakeMirror"]: GetContractReturnType<IPChainStakeMirror$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPChainStakeMirror.sol:IPChainStakeMirror"]: GetContractReturnType<IPChainStakeMirror$Type["abi"]>;
  }
}
