// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IRelay$Type } from "./IRelay";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRelay"]: IRelay$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRelay.sol:IRelay"]: IRelay$Type;
  }

  interface ContractTypesMap {
    ["IRelay"]: GetContractReturnType<IRelay$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRelay.sol:IRelay"]: GetContractReturnType<IRelay$Type["abi"]>;
  }
}
