// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MemoryTokens$Type } from "./MemoryTokens";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MemoryTokens"]: MemoryTokens$Type;
    ["contracts/MemoryTokens.sol:MemoryTokens"]: MemoryTokens$Type;
  }

  interface ContractTypesMap {
    ["MemoryTokens"]: GetContractReturnType<MemoryTokens$Type["abi"]>;
    ["contracts/MemoryTokens.sol:MemoryTokens"]: GetContractReturnType<MemoryTokens$Type["abi"]>;
  }
}
