// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoFeedIdConverter$Type } from "./IFtsoFeedIdConverter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoFeedIdConverter"]: IFtsoFeedIdConverter$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedIdConverter.sol:IFtsoFeedIdConverter"]: IFtsoFeedIdConverter$Type;
  }

  interface ContractTypesMap {
    ["IFtsoFeedIdConverter"]: GetContractReturnType<IFtsoFeedIdConverter$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedIdConverter.sol:IFtsoFeedIdConverter"]: GetContractReturnType<IFtsoFeedIdConverter$Type["abi"]>;
  }
}
