// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFtsoFeedIdConverter$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFtsoFeedIdConverter",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedIdConverter.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes21",
          "name": "_feedId",
          "type": "bytes21"
        }
      ],
      "name": "getFeedCategoryAndName",
      "outputs": [
        {
          "internalType": "uint8",
          "name": "_category",
          "type": "uint8"
        },
        {
          "internalType": "string",
          "name": "_name",
          "type": "string"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint8",
          "name": "_category",
          "type": "uint8"
        },
        {
          "internalType": "string",
          "name": "_name",
          "type": "string"
        }
      ],
      "name": "getFeedId",
      "outputs": [
        {
          "internalType": "bytes21",
          "name": "",
          "type": "bytes21"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFtsoFeedIdConverter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoFeedIdConverter$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedIdConverter.sol:IFtsoFeedIdConverter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoFeedIdConverter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFtsoFeedIdConverter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoFeedIdConverter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedIdConverter.sol:IFtsoFeedIdConverter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoFeedIdConverter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFtsoFeedIdConverter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoFeedIdConverter$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedIdConverter.sol:IFtsoFeedIdConverter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoFeedIdConverter$Type["abi"]>>;
}
