// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPChainStakeMirrorMultiSigVoting$Type } from "./IPChainStakeMirrorMultiSigVoting";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPChainStakeMirrorMultiSigVoting"]: IPChainStakeMirrorMultiSigVoting$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPChainStakeMirrorMultiSigVoting.sol:IPChainStakeMirrorMultiSigVoting"]: IPChainStakeMirrorMultiSigVoting$Type;
  }

  interface ContractTypesMap {
    ["IPChainStakeMirrorMultiSigVoting"]: GetContractReturnType<IPChainStakeMirrorMultiSigVoting$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPChainStakeMirrorMultiSigVoting.sol:IPChainStakeMirrorMultiSigVoting"]: GetContractReturnType<IPChainStakeMirrorMultiSigVoting$Type["abi"]>;
  }
}
