// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IVPContractEvents$Type } from "./IVPContractEvents";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVPContractEvents"]: IVPContractEvents$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IVPContractEvents.sol:IVPContractEvents"]: IVPContractEvents$Type;
  }

  interface ContractTypesMap {
    ["IVPContractEvents"]: GetContractReturnType<IVPContractEvents$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IVPContractEvents.sol:IVPContractEvents"]: GetContractReturnType<IVPContractEvents$Type["abi"]>;
  }
}
