// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IVPContractEvents$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IVPContractEvents",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IVPContractEvents.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "from",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "to",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "priorVotePower",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "newVotePower",
          "type": "uint256"
        }
      ],
      "name": "Delegate",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "delegator",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "address",
          "name": "delegatee",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "votePower",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "blockNumber",
          "type": "uint256"
        }
      ],
      "name": "Revoke",
      "type": "event"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IVPContractEvents",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IVPContractEvents$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IVPContractEvents.sol:IVPContractEvents",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IVPContractEvents$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IVPContractEvents",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IVPContractEvents$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IVPContractEvents.sol:IVPContractEvents",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IVPContractEvents$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IVPContractEvents",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IVPContractEvents$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IVPContractEvents.sol:IVPContractEvents",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IVPContractEvents$Type["abi"]>>;
}
