// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPayment$Type } from "./IPayment";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPayment"]: IPayment$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPayment.sol:IPayment"]: IPayment$Type;
  }

  interface ContractTypesMap {
    ["IPayment"]: GetContractReturnType<IPayment$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPayment.sol:IPayment"]: GetContractReturnType<IPayment$Type["abi"]>;
  }
}
