// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDistributionToDelegators$Type } from "./IDistributionToDelegators";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDistributionToDelegators"]: IDistributionToDelegators$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IDistributionToDelegators.sol:IDistributionToDelegators"]: IDistributionToDelegators$Type;
  }

  interface ContractTypesMap {
    ["IDistributionToDelegators"]: GetContractReturnType<IDistributionToDelegators$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IDistributionToDelegators.sol:IDistributionToDelegators"]: GetContractReturnType<IDistributionToDelegators$Type["abi"]>;
  }
}
