// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IIVPContract$Type } from "./IIVPContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IIVPContract"]: IIVPContract$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/token/interface/IIVPContract.sol:IIVPContract"]: IIVPContract$Type;
  }

  interface ContractTypesMap {
    ["IIVPContract"]: GetContractReturnType<IIVPContract$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/token/interface/IIVPContract.sol:IIVPContract"]: GetContractReturnType<IIVPContract$Type["abi"]>;
  }
}
