// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IGovernanceVotePower$Type } from "./IGovernanceVotePower";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IGovernanceVotePower"]: IGovernanceVotePower$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IGovernanceVotePower.sol:IGovernanceVotePower"]: IGovernanceVotePower$Type;
  }

  interface ContractTypesMap {
    ["IGovernanceVotePower"]: GetContractReturnType<IGovernanceVotePower$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IGovernanceVotePower.sol:IGovernanceVotePower"]: GetContractReturnType<IGovernanceVotePower$Type["abi"]>;
  }
}
