// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ProtocolsV2Interface$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ProtocolsV2Interface",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/ProtocolsV2Interface.sol",
  "abi": [
    {
      "inputs": [],
      "name": "firstRewardEpochStartTs",
      "outputs": [
        {
          "internalType": "uint64",
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "firstVotingRoundStartTs",
      "outputs": [
        {
          "internalType": "uint64",
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getCurrentRewardEpochId",
      "outputs": [
        {
          "internalType": "uint24",
          "name": "",
          "type": "uint24"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getCurrentVotingEpochId",
      "outputs": [
        {
          "internalType": "uint32",
          "name": "",
          "type": "uint32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_rewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "getStartVotingRoundId",
      "outputs": [
        {
          "internalType": "uint32",
          "name": "",
          "type": "uint32"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_rewardEpochId",
          "type": "uint256"
        }
      ],
      "name": "getVotePowerBlock",
      "outputs": [
        {
          "internalType": "uint64",
          "name": "_votePowerBlock",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "rewardEpochDurationSeconds",
      "outputs": [
        {
          "internalType": "uint64",
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "votingEpochDurationSeconds",
      "outputs": [
        {
          "internalType": "uint64",
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ProtocolsV2Interface",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ProtocolsV2Interface$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/ProtocolsV2Interface.sol:ProtocolsV2Interface",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ProtocolsV2Interface$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ProtocolsV2Interface",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ProtocolsV2Interface$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/ProtocolsV2Interface.sol:ProtocolsV2Interface",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ProtocolsV2Interface$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ProtocolsV2Interface",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ProtocolsV2Interface$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/ProtocolsV2Interface.sol:ProtocolsV2Interface",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ProtocolsV2Interface$Type["abi"]>>;
}
