// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoRegistryGenesis$Type } from "./IFtsoRegistryGenesis";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoRegistryGenesis"]: IFtsoRegistryGenesis$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoRegistryGenesis.sol:IFtsoRegistryGenesis"]: IFtsoRegistryGenesis$Type;
  }

  interface ContractTypesMap {
    ["IFtsoRegistryGenesis"]: GetContractReturnType<IFtsoRegistryGenesis$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoRegistryGenesis.sol:IFtsoRegistryGenesis"]: GetContractReturnType<IFtsoRegistryGenesis$Type["abi"]>;
  }
}
