// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFtsoRegistryGenesis$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFtsoRegistryGenesis",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoRegistryGenesis.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256[]",
          "name": "_indices",
          "type": "uint256[]"
        }
      ],
      "name": "getFtsos",
      "outputs": [
        {
          "internalType": "contract IFtsoGenesis[]",
          "name": "_ftsos",
          "type": "address[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFtsoRegistryGenesis",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoRegistryGenesis$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoRegistryGenesis.sol:IFtsoRegistryGenesis",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoRegistryGenesis$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFtsoRegistryGenesis",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoRegistryGenesis$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoRegistryGenesis.sol:IFtsoRegistryGenesis",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoRegistryGenesis$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFtsoRegistryGenesis",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoRegistryGenesis$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoRegistryGenesis.sol:IFtsoRegistryGenesis",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoRegistryGenesis$Type["abi"]>>;
}
