// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoManager$Type } from "./IFtsoManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoManager"]: IFtsoManager$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoManager.sol:IFtsoManager"]: IFtsoManager$Type;
  }

  interface ContractTypesMap {
    ["IFtsoManager"]: GetContractReturnType<IFtsoManager$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoManager.sol:IFtsoManager"]: GetContractReturnType<IFtsoManager$Type["abi"]>;
  }
}
