// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IRewardManager$Type } from "./IRewardManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRewardManager"]: IRewardManager$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRewardManager.sol:IRewardManager"]: IRewardManager$Type;
  }

  interface ContractTypesMap {
    ["IRewardManager"]: GetContractReturnType<IRewardManager$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRewardManager.sol:IRewardManager"]: GetContractReturnType<IRewardManager$Type["abi"]>;
  }
}
