// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IConfirmedBlockHeightExists$Type } from "./IConfirmedBlockHeightExists";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IConfirmedBlockHeightExists"]: IConfirmedBlockHeightExists$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IConfirmedBlockHeightExists.sol:IConfirmedBlockHeightExists"]: IConfirmedBlockHeightExists$Type;
  }

  interface ContractTypesMap {
    ["IConfirmedBlockHeightExists"]: GetContractReturnType<IConfirmedBlockHeightExists$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IConfirmedBlockHeightExists.sol:IConfirmedBlockHeightExists"]: GetContractReturnType<IConfirmedBlockHeightExists$Type["abi"]>;
  }
}
