// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoFeedDecimals$Type } from "./IFtsoFeedDecimals";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoFeedDecimals"]: IFtsoFeedDecimals$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedDecimals.sol:IFtsoFeedDecimals"]: IFtsoFeedDecimals$Type;
  }

  interface ContractTypesMap {
    ["IFtsoFeedDecimals"]: GetContractReturnType<IFtsoFeedDecimals$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoFeedDecimals.sol:IFtsoFeedDecimals"]: GetContractReturnType<IFtsoFeedDecimals$Type["abi"]>;
  }
}
