// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtso$Type } from "./IFtso";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtso"]: IFtso$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtso.sol:IFtso"]: IFtso$Type;
  }

  interface ContractTypesMap {
    ["IFtso"]: GetContractReturnType<IFtso$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtso.sol:IFtso"]: GetContractReturnType<IFtso$Type["abi"]>;
  }
}
