// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IRNatAccount$Type } from "./IRNatAccount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRNatAccount"]: IRNatAccount$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRNatAccount.sol:IRNatAccount"]: IRNatAccount$Type;
  }

  interface ContractTypesMap {
    ["IRNatAccount"]: GetContractReturnType<IRNatAccount$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRNatAccount.sol:IRNatAccount"]: GetContractReturnType<IRNatAccount$Type["abi"]>;
  }
}
