// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IRNatAccount$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IRNatAccount",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IRNatAccount.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "address[]",
          "name": "executors",
          "type": "address[]"
        }
      ],
      "name": "ClaimExecutorsSet",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "contract IERC20",
          "name": "token",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "ExternalTokenTransferred",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "bool",
          "name": "wrap",
          "type": "bool"
        }
      ],
      "name": "FundsWithdrawn",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "address",
          "name": "owner",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "contract IRNat",
          "name": "rNat",
          "type": "address"
        }
      ],
      "name": "Initialized",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "LockedAmountBurned",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "rNat",
      "outputs": [
        {
          "internalType": "contract IRNat",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "receivedRewards",
      "outputs": [
        {
          "internalType": "uint128",
          "name": "",
          "type": "uint128"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "withdrawnRewards",
      "outputs": [
        {
          "internalType": "uint128",
          "name": "",
          "type": "uint128"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IRNatAccount",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRNatAccount$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IRNatAccount.sol:IRNatAccount",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRNatAccount$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IRNatAccount",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRNatAccount$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IRNatAccount.sol:IRNatAccount",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRNatAccount$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IRNatAccount",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRNatAccount$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IRNatAccount.sol:IRNatAccount",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRNatAccount$Type["abi"]>>;
}
