// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Base64$Type } from "./Base64";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Base64"]: Base64$Type;
    ["@openzeppelin/contracts/utils/Base64.sol:Base64"]: Base64$Type;
  }

  interface ContractTypesMap {
    ["Base64"]: GetContractReturnType<Base64$Type["abi"]>;
    ["@openzeppelin/contracts/utils/Base64.sol:Base64"]: GetContractReturnType<Base64$Type["abi"]>;
  }
}
