// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Base64$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Base64",
  "sourceName": "@openzeppelin/contracts/utils/Base64.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c4e8e6e4791496385ec82335e522068fdceb11fc6a3ca2483cd2f79d883f0fcd64736f6c634300081c0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c4e8e6e4791496385ec82335e522068fdceb11fc6a3ca2483cd2f79d883f0fcd64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Base64",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Base64$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Base64.sol:Base64",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Base64$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Base64",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Base64$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Base64.sol:Base64",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Base64$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Base64",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Base64$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Base64.sol:Base64",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Base64$Type["abi"]>>;
}
