// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IVoterWhitelister$Type } from "./IVoterWhitelister";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVoterWhitelister"]: IVoterWhitelister$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IVoterWhitelister.sol:IVoterWhitelister"]: IVoterWhitelister$Type;
  }

  interface ContractTypesMap {
    ["IVoterWhitelister"]: GetContractReturnType<IVoterWhitelister$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IVoterWhitelister.sol:IVoterWhitelister"]: GetContractReturnType<IVoterWhitelister$Type["abi"]>;
  }
}
