// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFdcInflationConfigurations$Type } from "./IFdcInflationConfigurations";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFdcInflationConfigurations"]: IFdcInflationConfigurations$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFdcInflationConfigurations.sol:IFdcInflationConfigurations"]: IFdcInflationConfigurations$Type;
  }

  interface ContractTypesMap {
    ["IFdcInflationConfigurations"]: GetContractReturnType<IFdcInflationConfigurations$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFdcInflationConfigurations.sol:IFdcInflationConfigurations"]: GetContractReturnType<IFdcInflationConfigurations$Type["abi"]>;
  }
}
