// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFdcInflationConfigurations$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFdcInflationConfigurations",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFdcInflationConfigurations.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "_index",
          "type": "uint256"
        }
      ],
      "name": "getFdcConfiguration",
      "outputs": [
        {
          "components": [
            {
              "internalType": "bytes32",
              "name": "attestationType",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "source",
              "type": "bytes32"
            },
            {
              "internalType": "uint24",
              "name": "inflationShare",
              "type": "uint24"
            },
            {
              "internalType": "uint8",
              "name": "minRequestsThreshold",
              "type": "uint8"
            },
            {
              "internalType": "uint224",
              "name": "mode",
              "type": "uint224"
            }
          ],
          "internalType": "struct IFdcInflationConfigurations.FdcConfiguration",
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getFdcConfigurations",
      "outputs": [
        {
          "components": [
            {
              "internalType": "bytes32",
              "name": "attestationType",
              "type": "bytes32"
            },
            {
              "internalType": "bytes32",
              "name": "source",
              "type": "bytes32"
            },
            {
              "internalType": "uint24",
              "name": "inflationShare",
              "type": "uint24"
            },
            {
              "internalType": "uint8",
              "name": "minRequestsThreshold",
              "type": "uint8"
            },
            {
              "internalType": "uint224",
              "name": "mode",
              "type": "uint224"
            }
          ],
          "internalType": "struct IFdcInflationConfigurations.FdcConfiguration[]",
          "name": "",
          "type": "tuple[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFdcInflationConfigurations",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFdcInflationConfigurations$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcInflationConfigurations.sol:IFdcInflationConfigurations",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFdcInflationConfigurations$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFdcInflationConfigurations",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFdcInflationConfigurations$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcInflationConfigurations.sol:IFdcInflationConfigurations",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFdcInflationConfigurations$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFdcInflationConfigurations",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFdcInflationConfigurations$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFdcInflationConfigurations.sol:IFdcInflationConfigurations",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFdcInflationConfigurations$Type["abi"]>>;
}
