// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IAddressValidityVerification$Type } from "./IAddressValidityVerification";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAddressValidityVerification"]: IAddressValidityVerification$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IAddressValidityVerification.sol:IAddressValidityVerification"]: IAddressValidityVerification$Type;
  }

  interface ContractTypesMap {
    ["IAddressValidityVerification"]: GetContractReturnType<IAddressValidityVerification$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IAddressValidityVerification.sol:IAddressValidityVerification"]: GetContractReturnType<IAddressValidityVerification$Type["abi"]>;
  }
}
