// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IAddressValidityVerification$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IAddressValidityVerification",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IAddressValidityVerification.sol",
  "abi": [
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "bytes32[]",
              "name": "merkleProof",
              "type": "bytes32[]"
            },
            {
              "components": [
                {
                  "internalType": "bytes32",
                  "name": "attestationType",
                  "type": "bytes32"
                },
                {
                  "internalType": "bytes32",
                  "name": "sourceId",
                  "type": "bytes32"
                },
                {
                  "internalType": "uint64",
                  "name": "votingRound",
                  "type": "uint64"
                },
                {
                  "internalType": "uint64",
                  "name": "lowestUsedTimestamp",
                  "type": "uint64"
                },
                {
                  "components": [
                    {
                      "internalType": "string",
                      "name": "addressStr",
                      "type": "string"
                    }
                  ],
                  "internalType": "struct IAddressValidity.RequestBody",
                  "name": "requestBody",
                  "type": "tuple"
                },
                {
                  "components": [
                    {
                      "internalType": "bool",
                      "name": "isValid",
                      "type": "bool"
                    },
                    {
                      "internalType": "string",
                      "name": "standardAddress",
                      "type": "string"
                    },
                    {
                      "internalType": "bytes32",
                      "name": "standardAddressHash",
                      "type": "bytes32"
                    }
                  ],
                  "internalType": "struct IAddressValidity.ResponseBody",
                  "name": "responseBody",
                  "type": "tuple"
                }
              ],
              "internalType": "struct IAddressValidity.Response",
              "name": "data",
              "type": "tuple"
            }
          ],
          "internalType": "struct IAddressValidity.Proof",
          "name": "_proof",
          "type": "tuple"
        }
      ],
      "name": "verifyAddressValidity",
      "outputs": [
        {
          "internalType": "bool",
          "name": "_proved",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IAddressValidityVerification",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAddressValidityVerification$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressValidityVerification.sol:IAddressValidityVerification",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAddressValidityVerification$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IAddressValidityVerification",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAddressValidityVerification$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressValidityVerification.sol:IAddressValidityVerification",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAddressValidityVerification$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IAddressValidityVerification",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAddressValidityVerification$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressValidityVerification.sol:IAddressValidityVerification",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAddressValidityVerification$Type["abi"]>>;
}
