// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IDelegationAccount$Type } from "./IDelegationAccount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IDelegationAccount"]: IDelegationAccount$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IDelegationAccount.sol:IDelegationAccount"]: IDelegationAccount$Type;
  }

  interface ContractTypesMap {
    ["IDelegationAccount"]: GetContractReturnType<IDelegationAccount$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IDelegationAccount.sol:IDelegationAccount"]: GetContractReturnType<IDelegationAccount$Type["abi"]>;
  }
}
