// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFlareSystemsCalculator$Type } from "./IFlareSystemsCalculator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFlareSystemsCalculator"]: IFlareSystemsCalculator$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFlareSystemsCalculator.sol:IFlareSystemsCalculator"]: IFlareSystemsCalculator$Type;
  }

  interface ContractTypesMap {
    ["IFlareSystemsCalculator"]: GetContractReturnType<IFlareSystemsCalculator$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFlareSystemsCalculator.sol:IFlareSystemsCalculator"]: GetContractReturnType<IFlareSystemsCalculator$Type["abi"]>;
  }
}
