// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFlareSystemsCalculator$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFlareSystemsCalculator",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IFlareSystemsCalculator.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "voter",
          "type": "address"
        },
        {
          "indexed": true,
          "internalType": "uint24",
          "name": "rewardEpochId",
          "type": "uint24"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "delegationAddress",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint16",
          "name": "delegationFeeBIPS",
          "type": "uint16"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "wNatWeight",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "wNatCappedWeight",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "bytes20[]",
          "name": "nodeIds",
          "type": "bytes20[]"
        },
        {
          "indexed": false,
          "internalType": "uint256[]",
          "name": "nodeWeights",
          "type": "uint256[]"
        }
      ],
      "name": "VoterRegistrationInfo",
      "type": "event"
    },
    {
      "inputs": [],
      "name": "signingPolicySignNoRewardsDurationBlocks",
      "outputs": [
        {
          "internalType": "uint64",
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "signingPolicySignNonPunishableDurationBlocks",
      "outputs": [
        {
          "internalType": "uint64",
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "signingPolicySignNonPunishableDurationSeconds",
      "outputs": [
        {
          "internalType": "uint64",
          "name": "",
          "type": "uint64"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "wNatCapPPM",
      "outputs": [
        {
          "internalType": "uint24",
          "name": "",
          "type": "uint24"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFlareSystemsCalculator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFlareSystemsCalculator$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFlareSystemsCalculator.sol:IFlareSystemsCalculator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFlareSystemsCalculator$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFlareSystemsCalculator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFlareSystemsCalculator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFlareSystemsCalculator.sol:IFlareSystemsCalculator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFlareSystemsCalculator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFlareSystemsCalculator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFlareSystemsCalculator$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IFlareSystemsCalculator.sol:IFlareSystemsCalculator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFlareSystemsCalculator$Type["abi"]>>;
}
