// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoRegistry$Type } from "./IFtsoRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoRegistry"]: IFtsoRegistry$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoRegistry.sol:IFtsoRegistry"]: IFtsoRegistry$Type;
  }

  interface ContractTypesMap {
    ["IFtsoRegistry"]: GetContractReturnType<IFtsoRegistry$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IFtsoRegistry.sol:IFtsoRegistry"]: GetContractReturnType<IFtsoRegistry$Type["abi"]>;
  }
}
