// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IIncreaseManager$Type } from "./IIncreaseManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IIncreaseManager"]: IIncreaseManager$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IIncreaseManager.sol:IIncreaseManager"]: IIncreaseManager$Type;
  }

  interface ContractTypesMap {
    ["IIncreaseManager"]: GetContractReturnType<IIncreaseManager$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IIncreaseManager.sol:IIncreaseManager"]: GetContractReturnType<IIncreaseManager$Type["abi"]>;
  }
}
