// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IRandomProvider$Type } from "./IRandomProvider";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRandomProvider"]: IRandomProvider$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRandomProvider.sol:IRandomProvider"]: IRandomProvider$Type;
  }

  interface ContractTypesMap {
    ["IRandomProvider"]: GetContractReturnType<IRandomProvider$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IRandomProvider.sol:IRandomProvider"]: GetContractReturnType<IRandomProvider$Type["abi"]>;
  }
}
