// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IFtsoManagerGenesis$Type } from "./IFtsoManagerGenesis";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IFtsoManagerGenesis"]: IFtsoManagerGenesis$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoManagerGenesis.sol:IFtsoManagerGenesis"]: IFtsoManagerGenesis$Type;
  }

  interface ContractTypesMap {
    ["IFtsoManagerGenesis"]: GetContractReturnType<IFtsoManagerGenesis$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoManagerGenesis.sol:IFtsoManagerGenesis"]: GetContractReturnType<IFtsoManagerGenesis$Type["abi"]>;
  }
}
