// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IFtsoManagerGenesis$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IFtsoManagerGenesis",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoManagerGenesis.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getCurrentPriceEpochId",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "_priceEpochId",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IFtsoManagerGenesis",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoManagerGenesis$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoManagerGenesis.sol:IFtsoManagerGenesis",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IFtsoManagerGenesis$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IFtsoManagerGenesis",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoManagerGenesis$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoManagerGenesis.sol:IFtsoManagerGenesis",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IFtsoManagerGenesis$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IFtsoManagerGenesis",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoManagerGenesis$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/genesis/interface/IFtsoManagerGenesis.sol:IFtsoManagerGenesis",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IFtsoManagerGenesis$Type["abi"]>>;
}
