// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IAddressBinder$Type } from "./IAddressBinder";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IAddressBinder"]: IAddressBinder$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IAddressBinder.sol:IAddressBinder"]: IAddressBinder$Type;
  }

  interface ContractTypesMap {
    ["IAddressBinder"]: GetContractReturnType<IAddressBinder$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IAddressBinder.sol:IAddressBinder"]: GetContractReturnType<IAddressBinder$Type["abi"]>;
  }
}
