// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IAddressBinder$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IAddressBinder",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IAddressBinder.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "bytes",
          "name": "publicKey",
          "type": "bytes"
        },
        {
          "indexed": false,
          "internalType": "bytes20",
          "name": "pAddress",
          "type": "bytes20"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "cAddress",
          "type": "address"
        }
      ],
      "name": "AddressesRegistered",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_cAddress",
          "type": "address"
        }
      ],
      "name": "cAddressToPAddress",
      "outputs": [
        {
          "internalType": "bytes20",
          "name": "_pAddress",
          "type": "bytes20"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes20",
          "name": "_pAddress",
          "type": "bytes20"
        }
      ],
      "name": "pAddressToCAddress",
      "outputs": [
        {
          "internalType": "address",
          "name": "_cAddress",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "_publicKey",
          "type": "bytes"
        },
        {
          "internalType": "bytes20",
          "name": "_pAddress",
          "type": "bytes20"
        },
        {
          "internalType": "address",
          "name": "_cAddress",
          "type": "address"
        }
      ],
      "name": "registerAddresses",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "_publicKey",
          "type": "bytes"
        }
      ],
      "name": "registerPublicKey",
      "outputs": [
        {
          "internalType": "bytes20",
          "name": "_pAddress",
          "type": "bytes20"
        },
        {
          "internalType": "address",
          "name": "_cAddress",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IAddressBinder",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAddressBinder$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressBinder.sol:IAddressBinder",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IAddressBinder$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IAddressBinder",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAddressBinder$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressBinder.sol:IAddressBinder",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IAddressBinder$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IAddressBinder",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAddressBinder$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IAddressBinder.sol:IAddressBinder",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IAddressBinder$Type["abi"]>>;
}
