// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IBalanceDecreasingTransactionVerification$Type } from "./IBalanceDecreasingTransactionVerification";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IBalanceDecreasingTransactionVerification"]: IBalanceDecreasingTransactionVerification$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IBalanceDecreasingTransactionVerification.sol:IBalanceDecreasingTransactionVerification"]: IBalanceDecreasingTransactionVerification$Type;
  }

  interface ContractTypesMap {
    ["IBalanceDecreasingTransactionVerification"]: GetContractReturnType<IBalanceDecreasingTransactionVerification$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IBalanceDecreasingTransactionVerification.sol:IBalanceDecreasingTransactionVerification"]: GetContractReturnType<IBalanceDecreasingTransactionVerification$Type["abi"]>;
  }
}
