// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IClaimSetupManager$Type } from "./IClaimSetupManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IClaimSetupManager"]: IClaimSetupManager$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IClaimSetupManager.sol:IClaimSetupManager"]: IClaimSetupManager$Type;
  }

  interface ContractTypesMap {
    ["IClaimSetupManager"]: GetContractReturnType<IClaimSetupManager$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IClaimSetupManager.sol:IClaimSetupManager"]: GetContractReturnType<IClaimSetupManager$Type["abi"]>;
  }
}
