// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IPaymentVerification$Type } from "./IPaymentVerification";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPaymentVerification"]: IPaymentVerification$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPaymentVerification.sol:IPaymentVerification"]: IPaymentVerification$Type;
  }

  interface ContractTypesMap {
    ["IPaymentVerification"]: GetContractReturnType<IPaymentVerification$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IPaymentVerification.sol:IPaymentVerification"]: GetContractReturnType<IPaymentVerification$Type["abi"]>;
  }
}
