// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ScarfBank$Type } from "./ScarfBank";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ScarfBank"]: ScarfBank$Type;
    ["contracts/ScarfBank.sol:ScarfBank"]: ScarfBank$Type;
  }

  interface ContractTypesMap {
    ["ScarfBank"]: GetContractReturnType<ScarfBank$Type["abi"]>;
    ["contracts/ScarfBank.sol:ScarfBank"]: GetContractReturnType<ScarfBank$Type["abi"]>;
  }
}
