// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IValidatorRegistry$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IValidatorRegistry",
  "sourceName": "@flarenetwork/flare-periphery-contracts/coston2/IValidatorRegistry.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "dataProvider",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "string",
          "name": "nodeId",
          "type": "string"
        },
        {
          "indexed": false,
          "internalType": "string",
          "name": "pChainPublicKey",
          "type": "string"
        }
      ],
      "name": "DataProviderRegistered",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "address",
          "name": "dataProvider",
          "type": "address"
        }
      ],
      "name": "DataProviderUnregistered",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "_nodeId",
          "type": "bytes32"
        }
      ],
      "name": "getDataProviderForNodeId",
      "outputs": [
        {
          "internalType": "address",
          "name": "_dataProvider",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "_pChainPublicKey",
          "type": "bytes32"
        }
      ],
      "name": "getDataProviderForPChainPublicKey",
      "outputs": [
        {
          "internalType": "address",
          "name": "_dataProvider",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_dataProvider",
          "type": "address"
        }
      ],
      "name": "getDataProviderInfo",
      "outputs": [
        {
          "internalType": "string",
          "name": "_nodeId",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "_pChainPublicKey",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "string",
          "name": "_nodeId",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "_pChainPublicKey",
          "type": "string"
        }
      ],
      "name": "registerDataProvider",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "unregisterDataProvider",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IValidatorRegistry",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IValidatorRegistry$Type["abi"]>>;
  export function deployContract(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IValidatorRegistry.sol:IValidatorRegistry",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IValidatorRegistry$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IValidatorRegistry",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IValidatorRegistry$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IValidatorRegistry.sol:IValidatorRegistry",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IValidatorRegistry$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IValidatorRegistry",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IValidatorRegistry$Type["abi"]>>;
  export function getContractAt(
    contractName: "@flarenetwork/flare-periphery-contracts/coston2/IValidatorRegistry.sol:IValidatorRegistry",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IValidatorRegistry$Type["abi"]>>;
}
