// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EnumerableMap$Type } from "./EnumerableMap";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EnumerableMap"]: EnumerableMap$Type;
    ["@openzeppelin/contracts/utils/structs/EnumerableMap.sol:EnumerableMap"]: EnumerableMap$Type;
  }

  interface ContractTypesMap {
    ["EnumerableMap"]: GetContractReturnType<EnumerableMap$Type["abi"]>;
    ["@openzeppelin/contracts/utils/structs/EnumerableMap.sol:EnumerableMap"]: GetContractReturnType<EnumerableMap$Type["abi"]>;
  }
}
