// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IWNat$Type } from "./IWNat";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IWNat"]: IWNat$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IWNat.sol:IWNat"]: IWNat$Type;
  }

  interface ContractTypesMap {
    ["IWNat"]: GetContractReturnType<IWNat$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IWNat.sol:IWNat"]: GetContractReturnType<IWNat$Type["abi"]>;
  }
}
