// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IReferencedPaymentNonexistenceVerification$Type } from "./IReferencedPaymentNonexistenceVerification";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IReferencedPaymentNonexistenceVerification"]: IReferencedPaymentNonexistenceVerification$Type;
    ["@flarenetwork/flare-periphery-contracts/coston2/IReferencedPaymentNonexistenceVerification.sol:IReferencedPaymentNonexistenceVerification"]: IReferencedPaymentNonexistenceVerification$Type;
  }

  interface ContractTypesMap {
    ["IReferencedPaymentNonexistenceVerification"]: GetContractReturnType<IReferencedPaymentNonexistenceVerification$Type["abi"]>;
    ["@flarenetwork/flare-periphery-contracts/coston2/IReferencedPaymentNonexistenceVerification.sol:IReferencedPaymentNonexistenceVerification"]: GetContractReturnType<IReferencedPaymentNonexistenceVerification$Type["abi"]>;
  }
}
